### ISSUE TITLE
As a task creator, I need buttons that clarify what happens next. 

### ISSUE THREAD

**Issue by GailSwanson** [18F/openopps-platform#1008]
Task creators are confused about what happens next.  Even when "save as draft" is working, we expect that this issue will persist.  Lisa reports that she often needs to spend quite a bit of time walking people through the task creation workflow for them  to understand what is going on.

Note:  issue modified -- was "remove save as draft" so some of the comments refer to that

**Comment by dhcole** [comment]
I'm :+1: on this. @GailSwanson want to run this by @LisaLNelson?

**Comment by ultrasaurus** [comment]
Nooo!  please keep Save Draft

**Comment by ultrasaurus** [comment]
Ok, let me try for a more reasoned response.  People used to just post opportunities and they would go to Lisa for review.  There was a lot of feedback that that didn't work for people.  Repeat task creators would keep separate spreadsheets of their tasks in draft, which gave Lisa ZERO visibility and slowed down the process.  We've gotten users to change their behavior and start drafting in the platform.  Let's add the new workflow and not disrupt current user behavior.

Fine if @GailSwanson wants to refute my anecodotal evidence with more research, but otherwise let's not change "save draft"

**Comment by GailSwanson** [comment]
Unfortunately save draft does not currently save a draft. It submits it to
Lisa for review causing much confusion. We need to refactor the task flow
and states to get this functioning in a clear way. I absolutely want this
creature, but it requires a bit of work first.

**Comment by ultrasaurus** [comment]
Let's discuss at our meeting or schedule a different design session.

**Comment by ultrasaurus** [comment]
let's design what we need based on Friday's usability tests

**Comment by rogeruiz** [comment]
Duplicate ticket of #1143. Because the newer ticket has more information on the task, I'll be closing this one.
