### ISSUE TITLE
How do I set the open-opportunities theme?

### ISSUE THREAD

**Issue by Kazilico** [18F/openopps-platform#1151]
When I got midas working locally, it has the midas logo. When looking at #722, it looks like there is a theme to make it open opportunities. How do I activate the theme? Are there instructions that I am missing?

**Comment by rogeruiz** [comment]
Hey @Kazilico,

The theme repository doesn't necessarily need to be cloned on your local machine, but you could to see what is in the repo and what will be resynced over on `npm preinstall`

The command you'll need to set up the theme installation is in the `package.json` [here](https://github.com/18F/openopps-platform/blob/dev/package.json#L78) 

You will need to set up the environment variable in your shell before you run `npm install`

Setting the `$THEME` variable and running `npm install` will trigger the `preinstall` hook and will clone and rsync the contents of the theme project into the openopps-platform directory.

```
% THEME="https://github.com/18f/open-opportunities-theme/" npm install
```

**Comment by rogeruiz** [comment]
Hey @Kazilico,

To follow up on the theme installation, make sure you have the latest commits on the `dev` branch before attempting this. The project's renaming messed up the theme installation process and the fix is currently on the `dev` branch which wasn't up-to-date when you had originally opened this issue.

Please let me know if you have any issues running the steps I mentioned earlier. :smile:
