### ISSUE TITLE
All badges should show up on logged in home page

### ISSUE THREAD

**Issue by ultrasaurus** [18F/openopps-platform#1163]
Right now the logged in homepage (dashboard) only shows task completion badges.  Resolving this would show task creation badges.

**Comment by rogeruiz** [comment]
Taking a look at this a little deeper, I ended up [creating a new pull request here](https://github.com/18F/openopps-platform/pull/1165). @ultrasaurus pointed out that the `awardForTaskPublish` is being called from the lifecycle hook for the Tasks model, although it seems that it might not be getting called appropriately [since the code calling `awardForTaskPublish` does exist here](https://github.com/18F/openopps-platform/blob/dev/api/models/Task.js#L124).

**Comment by rogeruiz** [comment]
On further inspection, I've found that the issue is with the Waterline ORM where `.save` is non-transactional so `.update` is recommended to be used. But the other issue is that the original historical badges script doesn't update the `Task` model so the `afterUpdate` won't run. I believe it's best to stay within the nature of the original intentions, hooking into the lifecycle hooks of the model, and I will be looking into modifying this PR with a fix that allows for that.

**Comment by rogeruiz** [comment]
Closed by #1174
