### ISSUE TITLE
Application CSS & Theme CSS refactor; Theme / Platform synchronization / overrides

### ISSUE THREAD

**Issue by jeremiak** [18F/openopps-platform#906]
Currently, we only have only one CSS file that is used for the application instance. For Open Opportunities this means that we have a specific theme CSS that replaces the midas CSS. This introduces yet another place that we have to make CSS changes and has actually resulted in a few bugs.

We would prefer to have the CSS set up in such a way that the Midas CSS is used and any overriding of defaults occurs in the theme's CSS.

## List taken from @dhcole
- [x] Most of [this repo](https://github.com/18F/open-opportunities-theme) can be merged into the main application
- [x] Things like logos, home page image, translation file would need to be separate
- [x] Having those files extend / cascade default application files would avoid past issues with deployment
- [x] Currently files are rsync'd over the existing application files so everything needs to be duplicated in both files

**Comment by dhcole** [comment]
Capturing some ideas from standup:

- Most of this repo can be merged into the main application
- Things like logos, home page image, translation file would need to be separate
- Having those files extend / cascade default application files would avoid past issues with deployment
- Currently files are rsync'd over the existing application files so everything needs to be duplicated in both files

**Comment by rogeruiz** [comment]
I'm proposing that [this](https://github.com/18F/midas/issues/887) other ticket get merged or at least cross-referenced into the same pull request for this issue since they're related. Having a pre-processor, or "file funnel" as I like to call it, run through the current files and concat them can really lead the way to setting up an "*extend / cascade default app files*" much easier than refactoring the files first.

**Comment by ultrasaurus** [comment]
@rogeruiz feel free to add detail to the description of this ticket and close the other as a dup of this one.

**Comment by rogeruiz** [comment]
Keeping the discussion going with #887, to allow easier "defaults" and theming of the application I will be migrating the stylesheets to use Sass and Bourbon. The goal of this isn't to re-write all the styles for the project but rather have the original CSS files broken down into partials and also keep as much of the original CSS there run through the Sass preprocessor in order to best move forward making the stylesheets more modular.
